[package]
name = "steamos-mount-core"
version = "0.1.4"
edition = "2024"

[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }
snafu = { workspace = true }
dirs = "6"
nix = { version = "0.30", features = ["fs", "process", "signal", "user"] }
keyvalues-serde = "0.2"
hmac = "0.12"
sha2 = "0.10"
rand = "0.9"
hex = "0.4"

[dev-dependencies]
tempfile = "3"
